# Generated by Django 3.0.8 on 2020-10-18 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='listProdi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prodi', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='baseFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_baseFolder', models.CharField(default='', max_length=256)),
                ('prodi_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.listProdi')),
            ],
        ),
        migrations.CreateModel(
            name='baruFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('nama_folder', models.CharField(default='', max_length=256)),
                ('desc_folder', models.TextField(default='', max_length=256)),
                ('baseFolder_nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.baseFolder')),
                ('prodi_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.listProdi')),
            ],
        ),
        migrations.CreateModel(
            name='baruFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('nama_file', models.CharField(default='', max_length=256)),
                ('desc_file', models.TextField()),
                ('link_file', models.CharField(default='', max_length=256)),
                ('nama_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.baruFolder')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('prodi', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('FM', 'FM'), ('PS', 'PS')], default='Admin', max_length=255, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
