# Generated by Django 3.0.8 on 2020-10-25 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderUtama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('nama_folder', models.CharField(default='', max_length=256)),
                ('desc_folder', models.TextField(default='', max_length=256)),
                ('prodi_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.listProdi')),
            ],
        ),
        migrations.CreateModel(
            name='InformasiUmum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('nama_folder', models.CharField(default='', max_length=256)),
                ('desc_folder', models.TextField(default='', max_length=256)),
                ('baseFolder_nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FolderUtama')),
                ('prodi_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.listProdi')),
            ],
        ),
        migrations.CreateModel(
            name='AuditUmum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('nama_folder', models.CharField(default='', max_length=256)),
                ('desc_folder', models.TextField(default='', max_length=256)),
                ('baseFolder_nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FolderUtama')),
                ('prodi_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.listProdi')),
            ],
        ),
        migrations.CreateModel(
            name='AuditProdi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('nama_folder', models.CharField(default='', max_length=256)),
                ('desc_folder', models.TextField(default='', max_length=256)),
                ('baseFolder_nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FolderUtama')),
                ('prodi_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.listProdi')),
            ],
        ),
        migrations.CreateModel(
            name='AkreditasiUmum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('nama_folder', models.CharField(default='', max_length=256)),
                ('desc_folder', models.TextField(default='', max_length=256)),
                ('baseFolder_nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FolderUtama')),
                ('prodi_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.listProdi')),
            ],
        ),
        migrations.CreateModel(
            name='AkreditasiProdi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('nama_folder', models.CharField(default='', max_length=256)),
                ('desc_folder', models.TextField(default='', max_length=256)),
                ('baseFolder_nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FolderUtama')),
                ('prodi_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.listProdi')),
            ],
        ),
    ]
