# Generated by Django 3.1.2 on 2020-11-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bukupanduan_infoumumlain_peraturan_standarsekolah_standaruniv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barufile',
            name='link_file',
        ),
        migrations.AddField(
            model_name='barufile',
            name='upload_file',
            field=models.FileField(max_length=50, null=True, upload_to=''),
        ),
    ]
